### ISSUE TITLE
[bug] Appversion 10.5.3 does not start

### ISSUE THREAD

**Issue by pvannierop** [RADAR-base/RADAR-JDBC-Connector#26]
# Problem
With appversion v10.5.3 with RADAR-Kubernetes the JDBC-connector pods never reach the _ready_ state and throw the following error:

```
Expected 1 brokers but found only 0. Waiting 32 second before retrying ...
Exception in thread "main" java.io.IOException: Is a directory
        at java.base/sun.nio.ch.FileDispatcherImpl.read0(Native Method)
        at java.base/sun.nio.ch.FileDispatcherImpl.read(FileDispatcherImpl.java:48)
        at java.base/sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
        at java.base/sun.nio.ch.IOUtil.read(IOUtil.java:245)
        at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:223)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:65)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:107)
        at java.base/sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:101)
        at java.base/java.io.InputStream.read(InputStream.java:205)
        at java.base/java.util.Properties$LineReader.readLine(Properties.java:502)
        at java.base/java.util.Properties.load0(Properties.java:418)
        at java.base/java.util.Properties.load(Properties.java:407)
        at org.apache.kafka.common.utils.Utils.loadProps(Utils.java:669)
        at kafka.admin.BrokerApiVersionsCommand$.createAdminClient(BrokerApiVersionsCommand.scala:74)
        at kafka.admin.BrokerApiVersionsCommand$.execute(BrokerApiVersionsCommand.scala:60)
        at kafka.admin.BrokerApiVersionsCommand$.main(BrokerApiVersionsCommand.scala:55)
        at kafka.admin.BrokerApiVersionsCommand.main(BrokerApiVersionsCommand.scala)
Expected 1 brokers but found only 0. Waiting 32 second before retrying ...
```

The v10.5.2 version does not have this problem.

I have observed this problem both on the CI server as well as on local development running on HTTP (instead of HTTPS).

I suspect that the changed made in PR https://github.com/RADAR-base/RADAR-JDBC-Connector/pull/21 broke the container init.

**Comment by pvannierop** [comment]
Nevermind, this has been fixed in appversion 10.5.3-hotfix.
